version: '3.8'

services:
  backend:
    build:
      context: ./src/Backend
      dockerfile: Dockerfile
    volumes:
      - ./src/Backend:/app
    ports:
      - "8000:8000"
    command: python auth.py
    environment:
      - PORT=8000
    restart: unless-stopped
