version: "3.9"

services:
  backend:
    build:
      context: ./src/Backend
    container_name: app-backend
    ports:
      - "5000:5000"
    volumes:
      - ./src/Backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./src
    container_name: app-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app
    depends_on:
      - backend
    restart: unless-stopped
